# Generated by Django 6.0.3 on 2026-04-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Yetkazib berilgan Buyurtma',
                'verbose_name_plural': 'Yetkazib berilganlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Kutayotgan Buyurtma',
                'verbose_name_plural': 'Kutayotgan Buyurtmalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
