# Generated by Django 6.0.3 on 2026-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('retail', 'Chakana'), ('credit', 'Nasiya')], default='retail', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('processing', 'Tayyorlanmoqda'), ('shipped', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lanmagan"), ('paid', "To'langan"), ('failed', 'Xatolik'), ('refunded', 'Qaytarildi')], default='pending', max_length=10),
        ),
    ]
