# Generated by Django 6.0.3 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Onyx', max_length=100, verbose_name='Sayt nomi')),
                ('site_domain', models.CharField(default='onyx.uz', max_length=200, verbose_name='Domen / URL')),
                ('contact_email', models.EmailField(default='support@onyx.uz', max_length=254, verbose_name='Aloqa email')),
                ('contact_phone', models.CharField(blank=True, default='+998 71 200 00 00', max_length=50, verbose_name='Telefon raqam')),
                ('address', models.TextField(blank=True, default="Toshkent, O'zbekiston", verbose_name='Manzil')),
                ('receipt_footer', models.TextField(blank=True, default="Xarid uchun rahmat! Savol yoki muammo bo'lsa bizga murojaat qiling.", verbose_name='Chek pastki matni')),
                ('social_instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram URL')),
                ('social_telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram URL')),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
                'db_table': 'site_settings',
            },
        ),
    ]
