# Generated by Django 6.0.3 on 2026-04-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(default='Kelajak', help_text='Hero sarlavha 1-qator', max_length=100)),
                ('title_line2', models.CharField(default='elektronikasi', help_text='Hero sarlavha 2-qator', max_length=100)),
                ('title_line3', models.CharField(default='siz uchun.', help_text='Hero sarlavha 3-qator', max_length=100)),
                ('eyebrow_text', models.CharField(default='Yangi kolleksiya • 2026', help_text='Sarlavha ustidagi kichik matn', max_length=150)),
                ('subtitle', models.TextField(default="Eng so'nggi texnologiyalar, premium dizayn va ishonchli kafolat bilan.", help_text='Sarlavha ostidagi tavsif')),
                ('cta_primary_text', models.CharField(default='Xaridni boshlash', max_length=60)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero qismdagi chiroyli rasm (tavsiya: 1200x900)', null=True, upload_to='hero/')),
                ('badge_text', models.CharField(blank=True, default='🔥 Top Sotuvchi', help_text="Rasm ustidagi badge matni (bo'sh qoldirsa ko'rinmaydi)", max_length=60)),
                ('floating_card_title', models.CharField(blank=True, default='Rasmiy mahsulotlar', max_length=80)),
                ('floating_card_sub', models.CharField(blank=True, default='Kafolatlangan sifat', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Hero bo'limi",
                'verbose_name_plural': "Hero bo'limi",
                'db_table': 'hero_section',
            },
        ),
    ]
