# Generated by Django 6.0.3 on 2026-04-10 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero qismdagi chiroyli rasm (tavsiya: 1200x900)', null=True, upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
