# Generated by Django 6.0.3 on 2026-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_logo_url_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=10, help_text="Ombordagi qoldiq (agar variantlar bo'lmasa)"),
        ),
    ]
